#ifndef PORTS_H
#define PORTS_H

#define GREETER_PORT_DELTA 0
#define MULTIPLEXER_PORT_DELTA 1
#define REPLICATION_PORT_DELTA 3
#define HEARTBEAT_PORT_DELTA 2
#define ELECTION_MESSAGES_PORT_DELTA 4
#define ELECTION_RESPONSES_PORT_DELTA  5
#define SS_PORT_DELTA 6

#endif //PORTS_H