#ifndef PORTS_H
#define PORTS_H

#define GREETER_PORT_DELTA 0
#define MULTIPLEXER_PORT_DELTA 1
#define REPLICATION_PORT_DELTA 2
#define HEARTBEAT_PORT_DELTA 3
#define ELECTION_PASSIVE_PORT_DELTA 4
#define ELECTION_ACTIVE_PORT_DELTA  5

#endif //PORTS_H